-- Generated by Mocodo 4.2.10

CREATE TABLE CONTIENT (
  PRIMARY KEY (code_todo, code_tags),
  code_todo VARCHAR(42) NOT NULL,
  code_tags VARCHAR(42) NOT NULL
);

CREATE TABLE TAGS (
  PRIMARY KEY (code_tags),
  code_tags VARCHAR(42) NOT NULL,
  title     VARCHAR(42),
  color     VARCHAR(7)
);

CREATE TABLE TASKS (
  PRIMARY KEY (code_todo),
  code_todo   VARCHAR(42) NOT NULL,
  description VARCHAR(42),
  code_users  VARCHAR(42) NOT NULL
);

CREATE TABLE USERS (
  PRIMARY KEY (code_users),
  code_users VARCHAR(42) NOT NULL,
  name       VARCHAR(42)
);

ALTER TABLE CONTIENT ADD FOREIGN KEY (code_tags) REFERENCES TAGS (code_tags);
ALTER TABLE CONTIENT ADD FOREIGN KEY (code_todo) REFERENCES TASKS (code_todo);

ALTER TABLE TASKS ADD FOREIGN KEY (code_users) REFERENCES USERS (code_users);
